{
  Error error=new Error();
  try {
    inputFuture.setException(error);
    fail("Expected an Error to be thrown");
  }
 catch (  Error expected) {
    assertSame(error,expected);
  }
  listener.assertException(error);
}
