{
  try {
    getChecked(RUNTIME_EXCEPTION_FUTURE,TwoArgConstructorException.class,0,SECONDS);
    fail();
  }
 catch (  RuntimeException expected) {
    assertEquals(RUNTIME_EXCEPTION,expected);
  }
}
