{
  AsyncFunctionSpy<Throwable,Integer> fallback=spy(new AsyncFunction<Throwable,Integer>(){
    @Override public ListenableFuture<Integer> apply(    Throwable t) throws Exception {
      if (!wrapInFuture) {
        throw expectedException;
      }
 else {
        return immediateFailedFuture(expectedException);
      }
    }
  }
);
  ListenableFuture<Integer> failingFuture=immediateFailedFuture(new RuntimeException());
  ListenableFuture<Integer> faultTolerantFuture=catchingAsync(failingFuture,Throwable.class,fallback);
  try {
    getDone(faultTolerantFuture);
    fail();
  }
 catch (  ExecutionException expected) {
    assertSame(expectedException,expected.getCause());
  }
  fallback.verifyCallCount(1);
}
