{
  if (parameterIsPrimitiveOrNullable(func,paramIndex)) {
    return;
  }
  Object[] params=buildParamList(func,paramIndex);
  try {
    func.invoke(instance,params);
    Assert.fail("No exception thrown from " + func + Arrays.toString(params)+ " for "+ testedClass);
  }
 catch (  InvocationTargetException e) {
    Throwable cause=e.getCause();
    if (cause instanceof NullPointerException || cause instanceof UnsupportedOperationException) {
      return;
    }
    AssertionFailedError error=new AssertionFailedError("wrong exception thrown from " + func + ": "+ cause);
    error.initCause(cause);
    throw error;
  }
catch (  IllegalAccessException e) {
    throw new RuntimeException(e);
  }
catch (  InstantiationException e) {
    throw new RuntimeException(e);
  }
}
