{
  try {
    return get(key);
  }
 catch (  ExecutionException e) {
    wrapAndThrowUnchecked(e.getCause());
    throw new AssertionError();
  }
}
