{
  SomeThrowable cause=new SomeThrowable();
  SomeChainingException outer=new SomeChainingException(cause);
  StackTraceElement[] expectedTrace=outer.getStackTrace();
  try {
    Throwables.throwCause(outer,true);
    fail("Exception not thrown properly");
  }
 catch (  Throwable e) {
    assertSame(e,outer);
    assertTrue(Arrays.equals(expectedTrace,e.getStackTrace()));
  }
}
