{
  SettableFuture<Object> async=SettableFuture.create();
  SettableFuture<Object> inner=SettableFuture.create();
  async.setFuture(inner);
  async.cancel(false);
  assertTrue(inner.isCancelled());
  assertFalse(inner.wasInterrupted());
  try {
    inner.get();
    fail("Expected CancellationException");
  }
 catch (  CancellationException expected) {
  }
}
