{
  try {
    Futures.allAsList(immediateFailedFuture(new MyError())).get();
    fail();
  }
 catch (  ExecutionException e) {
    assertThat(e.getCause()).isInstanceOf(MyError.class);
    List<LogRecord> logged=aggregateFutureLogHandler.getStoredLogRecords();
    assertThat(logged).hasSize(1);
    assertThat(logged.get(0).getThrown()).isInstanceOf(MyError.class);
  }
}
