{
  try {
    get(FAILED_FUTURE_CHECKED_EXCEPTION,1,TimeUnit.SECONDS,ExceptionWithBadConstructor.class);
    fail();
  }
 catch (  IllegalArgumentException expected) {
    assertSame(CHECKED_EXCEPTION,expected.getCause());
  }
}
