{
  final MyException sameInstance=new MyException();
  SettableFuture<Object> firstFuture=SettableFuture.create();
  final SettableFuture<Object> secondFuture=SettableFuture.create();
  ListenableFuture<List<Object>> bulkFuture=allAsList(firstFuture,secondFuture);
  bulkFuture.addListener(new Runnable(){
    @Override public void run(){
      secondFuture.setException(sameInstance);
    }
  }
,directExecutor());
  firstFuture.setException(sameInstance);
  try {
    getDone(bulkFuture);
    fail();
  }
 catch (  ExecutionException expected) {
    assertThat(expected.getCause()).isInstanceOf(MyException.class);
    assertThat(aggregateFutureLogHandler.getStoredLogRecords()).isEmpty();
  }
}
