{
  try {
    MyException sameInstance=new MyException();
    Futures.allAsList(immediateFailedFuture(sameInstance),immediateFailedFuture(sameInstance)).get();
    fail();
  }
 catch (  ExecutionException e) {
    assertThat(e.getCause()).isInstanceOf(MyException.class);
    assertEquals("Nothing should be logged",0,aggregateFutureLogHandler.getStoredLogRecords().size());
  }
}
